/* SPDX-License-Identifier: MIT */
/*
 * Microfoam - Ed25519 conformance harness.
 *
 * Reads test vectors generated by the host tool and checks the C verifier
 * against them. Verification code is only as good as its test vectors, and the
 * ones that matter are the ones produced by a completely different
 * implementation.
 *
 * Usage: ed25519_test <vectors.bin>
 *
 * Vector file layout, all little-endian uint32 unless noted:
 *   u32 count
 *   count x { u32 msg_len; u32 key_len(32); u32 sig_len(64);
 *             u32 expect;  msg[]; key[32]; sig[64] }
 */

#include "mcf_ed25519.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_MSG 4096

static uint8_t g_buf[MAX_MSG + 128];

static uint32_t rd32(const uint8_t *p)
{
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) |
           ((uint32_t)p[3] << 24);
}

int main(int argc, char **argv)
{
    FILE   *f;
    uint8_t *file;
    long    size;
    uint32_t count, i;
    int     fail = 0;
    int     pass = 0;

    if (argc != 2) {
        printf("usage: ed25519_test <vectors.bin>\n");
        return 2;
    }

    f = fopen(argv[1], "rb");
    if (f == NULL) {
        printf("cannot open %s\n", argv[1]);
        return 2;
    }
    fseek(f, 0, SEEK_END);
    size = ftell(f);
    fseek(f, 0, SEEK_SET);
    file = (uint8_t *)malloc((size_t)size);
    if (file == NULL || fread(file, 1, (size_t)size, f) != (size_t)size) {
        printf("cannot read vectors\n");
        fclose(f);
        return 2;
    }
    fclose(f);

    count = rd32(file);

    printf("ed25519: %u vectors\n", count);
    {
        size_t off = 4;
        for (i = 0; i < count; i++) {
            uint32_t msg_len = rd32(&file[off]);  off += 4;
            uint32_t key_len = rd32(&file[off]);  off += 4;
            uint32_t sig_len = rd32(&file[off]);  off += 4;
            uint32_t expect = rd32(&file[off]);  off += 4;
            const uint8_t *msg = &file[off];      off += msg_len;
            const uint8_t *key = &file[off];      off += key_len;
            const uint8_t *sig = &file[off];      off += sig_len;
            int got;

            if (msg_len > MAX_MSG) {
                printf("  vector %u: message too long\n", i);
                return 2;
            }

            got = mcf_ed25519_verify(sig, msg, msg_len, key);
            if (got == (int)expect) {
                pass++;
            } else {
                printf("  FAIL vector %u: len=%u expect=%u got=%d\n",
                       i, msg_len, expect, got);
                fail++;
            }
        }
    }

    /* Fixed SHA-512 vectors, independent of the Ed25519 path. */
    {
        static const uint8_t empty[64] = {
            0xcf, 0x83, 0xe1, 0x35, 0x7e, 0xef, 0xb8, 0xbd, 0xf1, 0x54, 0x28, 0x50,
            0xd6, 0x6d, 0x80, 0x07, 0xd6, 0x20, 0xe4, 0x05, 0x0b, 0x57, 0x15, 0xdc,
            0x83, 0xf4, 0xa9, 0x21, 0xd3, 0x6c, 0xe9, 0xce, 0x47, 0xd0, 0xd1, 0x3c,
            0x5d, 0x85, 0xf2, 0xb0, 0xff, 0x83, 0x18, 0xd2, 0x87, 0x7e, 0xec, 0x2f,
            0x63, 0xb9, 0x31, 0xbd, 0x47, 0x41, 0x7a, 0x81, 0xa5, 0x38, 0x32, 0x7a,
            0xf9, 0x27, 0xda, 0x3e
        };
        static const uint8_t abc[64] = {
            0xdd, 0xaf, 0x35, 0xa1, 0x93, 0x61, 0x7a, 0xba, 0xcc, 0x41, 0x73, 0x49,
            0xae, 0x20, 0x41, 0x31, 0x12, 0xe6, 0xfa, 0x4e, 0x89, 0xa9, 0x7e, 0xa2,
            0x0a, 0x9e, 0xee, 0xe6, 0x4b, 0x55, 0xd3, 0x9a, 0x21, 0x92, 0x99, 0x2a,
            0x27, 0x4f, 0xc1, 0xa8, 0x36, 0xba, 0x3c, 0x23, 0xa3, 0xfe, 0xeb, 0xbd,
            0x45, 0x4d, 0x44, 0x23, 0x64, 0x3c, 0xe8, 0x0e, 0x2a, 0x9a, 0xc9, 0x4f,
            0xa5, 0x4c, 0xa4, 0x9f
        };
        uint8_t out[64];

        mcf_sha512(out, (const uint8_t *)"", 0u);
        if (memcmp(out, empty, 64) == 0) { pass++; }
        else { printf("  FAIL sha512(\"\")\n"); fail++; }

        mcf_sha512(out, (const uint8_t *)"abc", 3u);
        if (memcmp(out, abc, 64) == 0) { pass++; }
        else { printf("  FAIL sha512(\"abc\")\n"); fail++; }
    }

    /* NULL and degenerate inputs must be rejected, not crash. */
    {
        uint8_t key[32];
        uint8_t sig[64];
        int ok = 1;

        memset(key, 0x11, sizeof(key));
        memset(sig, 0x22, sizeof(sig));
        ok &= (mcf_ed25519_verify(sig, g_buf, 4u, key) == 0);
        ok &= (mcf_ed25519_verify(NULL, g_buf, 4u, key) == 0);
        ok &= (mcf_ed25519_verify(sig, NULL, 4u, key) == 0);
        ok &= (mcf_ed25519_verify(sig, g_buf, 4u, NULL) == 0);
        memset(key, 0, sizeof(key));
        ok &= (mcf_ed25519_verify(sig, g_buf, 4u, key) == 0);
        memset(sig, 0, sizeof(sig));
        ok &= (mcf_ed25519_verify(sig, g_buf, 4u, key) == 0);
        if (ok) { pass++; } else { printf("  FAIL degenerate inputs\n"); fail++; }
    }

    free(file);
    printf("%d passed, %d failed\n", pass, fail);
    return (fail == 0) ? 0 : 1;
}
