/* SPDX-License-Identifier: MIT */
/*
 * Microfoam - LZMA conformance harness.
 *
 * Reads vectors produced by host/lzma_vectors.py, which are generated by
 * liblzma via Python's lzma module, and checks the C decoder against the
 * expected plaintext.
 *
 * The vector set deliberately covers what the decoder can get wrong: the
 * literal state machine in both its plain and match-byte forms, repeated
 * distances, the position-slot and alignment trees, a dictionary smaller than
 * the input so the ring wraps repeatedly, and the full legal lc/lp/pb range,
 * because the probability table size and the literal state index both depend on
 * those fields.
 *
 * Usage: lzma_test <vectors.bin> <plaintexts-dir>
 *   vectors carry properties, compressed data, and a CRC of the expected
 *   plaintext, so the harness is self-contained.
 */

#include "mcf_internal.h"
#include "mcf_lzma.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_PLAIN 65536u

static int g_pass;
static int g_fail;

static uint32_t rd32(const uint8_t *p)
{
    return (uint32_t)p[0] | ((uint32_t)p[1] << 8) | ((uint32_t)p[2] << 16) |
           ((uint32_t)p[3] << 24);
}

/* Drive the decoder the way the session does: repeatedly, into a block-sized
 * buffer, over the whole stream, until finish() accepts. */
static int32_t run_vector(const uint8_t *props, uint32_t props_len,
                          const uint8_t *data, uint32_t data_len,
                          const uint8_t *expect, uint32_t expect_len,
                          const char *name, uint32_t block)
{
    static uint8_t out[MAX_PLAIN];
    static uint8_t *ws;
    static uint32_t ws_cap;
    mcf_codec_t *codec;
    uint32_t     need;
    uint32_t     pos = 0;
    uint32_t     total = 0;
    int32_t      r;

    need = mcf_lzma_workspace(props, props_len);
    if (need == 0u) {
        printf("  FAIL %-16s workspace reported 0\n", name);
        return -1;
    }
    if (ws == NULL || need > ws_cap) {
        uint8_t *n = (uint8_t *)realloc(ws, need);
        if (n == NULL) {
            printf("  FAIL %-16s out of memory\n", name);
            return -1;
        }
        ws = n;
        ws_cap = need;
    }

    /* Poison the workspace before every vector. The decoder must initialise all
     * of its own state; reusing one buffer across vectors without this hid an
     * uninitialised field for a long time, because a calloc'd harness makes
     * uninitialised memory read as zero and therefore appear correct. */
    memset(ws, 0xA5, need);

    codec = NULL;
    r = mcf_lzma_init(&codec, props, props_len, ws);
    if (r != MCF_OK || codec == NULL) {
        printf("  FAIL %-16s init returned %d\n", name, (int)r);
        return -1;
    }

    while (pos < data_len && total < expect_len) {
        uint32_t cap = expect_len - total;
        uint32_t produced = 0;
        uint32_t consumed = 0;

        if (cap > block) {
            cap = block;
        }
        /* The LZMA range coder owns its input cursor, so it is handed the
         * stream base and its full length on every call. LZ4 would want the
         * sliding window instead; see mcf_lzma.h. */
        r = mcf_lzma_decode(codec, out + total, cap, &produced, data, data_len,
                            &consumed);
        if (r != MCF_OK) {
            printf("  FAIL %-16s decode returned %d after %u bytes\n",
                   name, (int)r, total);
            return -1;
        }
        pos += consumed;
        total += produced;
        if (produced == 0u && consumed == 0u) {
            break;
        }
    }

    r = mcf_lzma_finish(codec);
    if (r != MCF_OK) {
        printf("  FAIL %-16s finish returned %d, produced %u of %u\n",
               name, (int)r, total, expect_len);
        return -1;
    }
    if (total != expect_len) {
        printf("  FAIL %-16s produced %u, expected %u\n", name, total, expect_len);
        return -1;
    }
    if (memcmp(out, expect, expect_len) != 0) {
        uint32_t i;
        for (i = 0; i < expect_len; i++) {
            if (out[i] != expect[i]) {
                break;
            }
        }
        printf("  FAIL %-16s differs at byte %u (got %02x want %02x)\n",
               name, i, out[i], expect[i]);
        return -1;
    }
    return 0;
}

int main(int argc, char **argv)
{
    FILE    *f;
    uint8_t *blob;
    long     size;
    uint32_t count, i;
    size_t   off;
    static uint8_t props[16];
    static uint8_t data[1 << 20];
    static uint8_t plain[MAX_PLAIN];
    /* Block sizes the session might plausibly use. Decoding must be identical
     * regardless of how the output is chunked, because a match can straddle
     * any boundary. */
    static const uint32_t blocks[] = { 256u, 512u, 1024u, 4096u, 65536u };

    if (argc != 2) {
        printf("usage: lzma_test <vectors.bin>\n");
        return 2;
    }
    f = fopen(argv[1], "rb");
    if (f == NULL) {
        printf("cannot open %s\n", argv[1]);
        return 2;
    }
    fseek(f, 0, SEEK_END);
    size = ftell(f);
    fseek(f, 0, SEEK_SET);
    blob = (uint8_t *)malloc((size_t)size);
    if (blob == NULL || fread(blob, 1, (size_t)size, f) != (size_t)size) {
        printf("cannot read vectors\n");
        fclose(f);
        return 2;
    }
    fclose(f);

    count = rd32(blob);
    off   = 4;
    printf("lzma: %u vectors, %u block sizes each\n", count,
           (uint32_t)(sizeof(blocks) / sizeof(blocks[0])));

    for (i = 0; i < count; i++) {
        uint32_t props_len = rd32(&blob[off]); off += 4;
        uint32_t data_len  = rd32(&blob[off]); off += 4;
        uint32_t plain_len = rd32(&blob[off]); off += 4;
        uint32_t b;
        char     name[32];

        if (props_len > sizeof(props) || data_len > sizeof(data) ||
            plain_len > sizeof(plain)) {
            printf("  vector %u too large\n", i);
            g_fail++;
            break;
        }
        memcpy(props, &blob[off], props_len); off += props_len;
        memcpy(data,  &blob[off], data_len);  off += data_len;
        memcpy(plain, &blob[off], plain_len); off += plain_len;

        for (b = 0; b < (sizeof(blocks) / sizeof(blocks[0])); b++) {
            snprintf(name, sizeof(name), "v%u/b%u", i, blocks[b]);
            if (run_vector(props, props_len, data, data_len, plain, plain_len,
                           name, blocks[b]) == 0) {
                g_pass++;
            } else {
                g_fail++;
            }
        }
    }

    printf("%d passed, %d failed\n", g_pass, g_fail);
    free(blob);
    return (g_fail == 0) ? 0 : 1;
}
